name: Test WorkFlow

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: 🐍 Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: 🦾 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
      - name: 🧹 Lint with flake8
        run: |
          make check_code_quality
      - name: 🧪 Test
        run: "python -m pytest ./test"
